# Dependencies
markdown:         kramdown
highlighter:      rouge # changed from `pygments` as github says so

# Permalinks
permalink:        pretty

# Setup
title:            'Shreyas R H'
tagline:          'Senior Software Engineer @Practo'
description:      ''
url:              
baseurl:          ''
paginate:         5
paginate_path:    ''

author:
  name: 'Shreyas'
  email: 'shreyas.rh9@gmail.com'
  github: shreyasrh9
  twitter: 
  linkedin: shreyas-r-h-8a74b8a2
  facebook: 
  goodreads: 
  orcid:  
  google_scholar: 
  email_md5: 
  emailalt_md5: 
  disqus_shortname: shreyas
  google_analytics_id: 
  google_analytics_url: 
  bio: 

theme: jekyll-theme-tactile